name: ar
description: Development of an mobile application using Flutter for the valorization of archaeological finds in the urban environment of the Ancona’s city,
             throught the use of  ‘gamification’.
repository: "https://github.com/Andreafaccenda/ArFlutter"

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Firebase dependencies
  google_sign_in: ^6.1.4
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  firebase_image: ^1.1.1
  firebase_auth: ^3.11.2
  firebase_storage: ^10.3.11
  # Mapbox dependencies
  flutter_map: any
  flutter_map_location_marker: any
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  latlong2: ^0.8.0
  location: ^5.0.3
  flutter_mapbox_navigation:
    git: https://github.com/Andreafaccenda/flutter_mapbox_navigator
  # Ar dependecies
  ar_flutter_plugin:
    git: https://github.com/Andreafaccenda/ar_flutter_plugin
  geoflutterfire: ^3.0.2
  #Other dependecies
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  hidden_drawer_menu: ^3.0.1
  http: any
  dio: ^4.0.4
  webview_flutter: ^2.8.0
  get: ^4.6.5
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.1.0
  simple_animation_progress_bar: ^1.6.0
  google_fonts: ^4.0.4
  connectivity_plus: ^4.0.2
  intl: ^0.17.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/config/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf

